add new rookout chart
Rookout/helm-charts pull request #65
Opened 2022-10-11 12:19 UTC by alexeygutkin

2022-10-11 12:20 UTC, alexeygutkin commented
/jira open task

2022-10-12 07:18 UTC, idanrookout commented on .github/workflows/publish.yml
> -          helm init -c --stable-repo-url https://charts.helm.sh/stable
we don't need it anymore?

2022-10-12 08:19 UTC, alexeygutkin commented on .github/workflows/publish.yml
> -          helm init -c --stable-repo-url https://charts.helm.sh/stable
init deprecated in helm 3

2022-10-12 12:19 UTC, lirook requested changes

2022-10-12 12:19 UTC, lirook commented on README.md
> +[rookout](https://github.com/rookout/helm-charts/tree/master/charts/rookout) - Rookout's hybrid deployment components (ETL Controller + Datastore)
Add a (deprecated) on line 19 and 17

2022-10-12 12:19 UTC, lirook commented
I left just one note, other than that if this is a copy paste from the other branch, it looks good to me

2022-10-16 09:49 UTC, idanrookout submitted a review, later dismissed

2022-10-16 10:13 UTC, idanrookout approved these changes

2022-10-19 12:24 UTC, gosharo approved these changes

2022-10-25 07:34 UTC, idanrookout approved these changes

2022-10-25 07:44 UTC, lirook approved these changes

2022-10-25 08:50 UTC, merged