fix:node port added to hybrid chart
Rookout/helm-charts pull request #68
Opened 2022-11-01 15:45 UTC by gosharo

/jira open task

2022-11-02 06:54 UTC, alexeygutkin requested changes

2022-11-02 06:54 UTC, alexeygutkin commented on charts/rookout-hybrid/templates/datastore-service.yaml
> +    {{- if eq datastore.service.type "NodePort" }}
we have to add it to controller too

2022-11-02 07:56 UTC, lirook commented on charts/rookout-hybrid/values.yaml
> +    #nodePort:
What's this?

2022-11-02 07:57 UTC, lirook commented on charts/rookout-hybrid/values.yaml
> +    #nodePort:
Let's add a better explanation here

2022-11-15 15:15 UTC, alexeygutkin submitted a review, later dismissed

2022-11-15 17:07 UTC, gosharo commented
/jira open task

2022-11-17 10:18 UTC, alexeygutkin approved these changes

2022-11-17 10:23 UTC, gosharo commented
/jira open task

2022-11-17 11:48 UTC, gosharo commented
/jira open task

2022-11-17 11:50 UTC, gosharo commented
[RK-15625](https://rookout.atlassian.net/browse/RK-15625)

2022-11-17 12:01 UTC, merged