hybrid chart secret support
Rookout/helm-charts pull request #76
Opened 2022-12-08 12:16 UTC by gosharo

- added secret support
- added secret support
- chart version bump
- chart version bump
- typos
- redame update

2022-12-13 13:46 UTC, idanrookout requested changes

2022-12-13 13:46 UTC, idanrookout commented on charts/controller/templates/deployment.yaml
> +            - name: ROOKOUT_SKIP_SSL_VERIFY
@naomirookout why is this here?

2022-12-14 05:50 UTC, gosharo commented
@naomirookout waiting for your approve for reviewing the documentation

2022-12-14 12:33 UTC, naomirookout commented on charts/controller/templates/deployment.yaml
> +            - name: ROOKOUT_SKIP_SSL_VERIFY
this was a mistake.

2022-12-14 15:28 UTC, merged