fix: remove unused memorydb flag
Rookout/helm-charts pull request #84
Opened 2023-03-14 08:24 UTC by gosharo

2023-03-14 08:24 UTC, gosharo commented
/jira open task

2023-03-14 08:30 UTC, alexeygutkin commented
https://github.com/Rookout/helm-charts/blob/master/charts/rookout-hybrid/templates/datastore-deployment.yaml#L76 why you are not removing it from here?

2023-03-14 11:22 UTC, gosharo commented
> https://github.com/Rookout/helm-charts/blob/master/charts/rookout-hybrid/templates/datastore-deployment.yaml#L76 why you are not removing it from here?

nope.

2023-03-14 13:48 UTC, Urook commented
> > https://github.com/Rookout/helm-charts/blob/master/charts/rookout-hybrid/templates/datastore-deployment.yaml#L76 why you are not removing it from here?
> 
> removed, it's true by default

@gosharo I think he means you should delete it from:
[The README](https://github.com/Rookout/helm-charts/blob/32bf4245616b2e8e277433368e73f7fd2e9be0f3/charts/rookout-hybrid/README.md?plain=1#L109)

2023-03-14 14:45 UTC, Urook requested changes

2023-03-14 14:45 UTC, Urook commented on charts/rookout-hybrid/README.md
> +![Version: 0.3.1](https://img.shields.io/badge/Version-0.1.0-informational?style=flat-square) ![Type: application](https://img.shields.io/badge/Type-application-informational?style=flat-square)
Why is the url still Version-0.1.p-informational?

2023-03-14 14:45 UTC, Urook commented on charts/rookout-hybrid/README.md
> -```
Why did you delete this?

2023-03-15 10:55 UTC, alexeygutkin approved these changes, later dismissed

2023-03-15 13:53 UTC, gosharo commented on charts/rookout-hybrid/README.md
> -```
not intended

2023-03-15 14:10 UTC, Urook requested changes

2023-03-15 15:08 UTC, Urook approved these changes

2023-03-15 15:08 UTC, merged